import MuiThemeProvider from "@/components/muiComponents/MuiTheme";
import NavBar from "../components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import { ContextProvider } from "@/Context/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gurommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ContextProvider>
        <MuiThemeProvider>
          <body>
            <NavBar />
            {children}
          </body>
        </MuiThemeProvider>
      </ContextProvider>
    </html>
  );
}
